# pnpm install on node 18, switch to frontend/ and pnpm exec ember build

# upload it to cloudflare pages afterward using wrangler


# use ubuntu 20.04
dist: focal
os: linux

# use vm based travis workers
virt: vm

# use arm64 based travis workers
arch:
  - arm64-graviton2

# use latest stable nodejs release
language: node_js
node_js:
  - node

# cache pnpm and corepack
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
    - "~/.cache/node/corepack"

# pnpm install
before_install:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir ~/.pnpm-store

# install, build and test
install:
  - pnpm install
script:
  - ./.ci-build.sh
after_success: 
  - ./.ci-deploy.sh