plugins:
  - path: .yarn/plugins/plugin-ignore-add-options.cjs
    spec: .yarn/unplugged/yarn-plugin-ignore-add-options-npm-0.1.0-8bafa29dba/node_modules/yarn-plugin-ignore-add-options/ignore-add-options-0.1.0.js

yarnPath: .yarn/releases/yarn-3.5.1.cjs
