workspace = { members = ["entities", "migrations"] }
[package]
name = "articleman"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "0.12", features = [
	"sqlx-postgres",
	"runtime-tokio-rustls",
	"macros",
	"with-uuid",
	"with-time",
	"with-json",
	"with-json",
] }
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
