name: Frontend Deployer

on:
   push:
      paths:
         - "app/frontend/**"

# Install and cache all bun dependencies

jobs:
   build_frontend:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [18]
      steps:
         - uses: actions/checkout@v4
         - uses: oven-sh/setup-bun@v1
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3
           with:
              node-version: ${{ matrix.node-version }}
         - name: Install dependencies
           run: bun install
           working-directory: app/frontend
         - name: Build the frontend
           run: bun run build
           working-directory: app/frontend
         - name: Deploy to Pages
           uses: cloudflare/wrangler-action@v3
           with:
              apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
              accountId: ${{ secrets.CF_PAGES_ACCOUNT_ID }}
              command: pages deploy --project-name=articleman --branch=main app/frontend/build
