name: Cloudflare Pages Deployer

on: push

# Install and cache all bun dependencies

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: bun install
    - name: Build for development
      run: ./.ci-build.sh
    - name: Deploy to Pages
      run: ./.ci-deploy.sh
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_PAGES_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_PAGES_ACCOUNT_ID }}
        CLOUDFLARE_PAGES_BRANCH: ${{ vars.CF_PAGES_BRANCH }}
        CLOUDFLARE_PAGES_NAME: ${{ vars.CF_PAGES_NAME }}